
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - base
patches: 
  - deploy.yaml
generatorOptions:
  disableNameSuffixHash: true  
configMapGenerator:
  - name: grafana-config
    namespace: demo
    files:
      - grafana.ini