apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - https://github.com/prometheus-operator/kube-prometheus.git?ref=release-0.4
generatorOptions:
  disableNameSuffixHash: true
resources:
  - resources/database.yaml
patchesStrategicMerge:
  - patches/0namespace-namespace.yaml
  - patches/prometheus-prometheus.yaml
  - patches/prometheus-clusterRole.yaml  
  - patches/grafana-deployment.yaml
  # - patches/grafana-DashboardSources.yaml  
configMapGenerator:
  - name: grafana-config
    namespace: monitoring
    files:
      - resources/grafana.ini  
