apiVersion: v1
kind: Service
metadata:
  name: database
  namespace: monitoring
spec:
  type: ClusterIP
  selector:
    app: database
  ports:
  - port: 5432
    targetPort: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      # volumes:
      #   - name: postgres-data
      #     emptyDir: {}
      containers:
      - name: database
        image: postgres:13.2
        resources:
          limits:
            cpu: "2"
            memory: 2Gi
          requests:
            cpu: "512m"
            memory: 1Gi
        ports:
          - containerPort: 5432
            name: postgres
        env:
          - name: POSTGRES_PASSWORD
            value: grafana
          - name: POSTGRES_USER
            value: grafana
          - name: POSTGRES_DB
            value: grafana      
        # volumeMounts:
        #   - mountPath: /var/lib/postgresql/data
        #     name: postgres-data  
